name: CI/CD Pipeline  # Name of the workflow

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the "main" branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Specify the environment to run the job

    steps:
      - name: Checkout code  # Step 1: Pull the code from the repository
        uses: actions/checkout@v3

      - name: Set up Node.js  # Step 2: Install the correct Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and test backend  # Step 3: Install and test the backend
        working-directory: ./backend
        run: |
          npm install
          node index.js  # Start the server to ensure it runs correctly

      - name: Deploy to Render  # Step 4: Deploy the application
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}  # Use a secret for the API key
        run: |
          # Assuming you use Render’s CLI for deployment
          render.yaml deploy